security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        public_area:
            pattern: ^/login|^/register|^/$
            security: false

        main:
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_homepage  # La redirection après la connexion 
            
            logout:
                path: app_logout
                target: app_homepage  # La redirection après la déconnexion


            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                remember_me_parameter: _remember_me

            entry_point: App\Security\LoginAuthenticator

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
